### ISSUE TITLE
Please add cookies

### ISSUE THREAD

**Issue by Yiming828** [FaridLU/fgrequests#3]
Please add support for cookies

**Comment by FaridLU** [comment]
@Yiming828 after `build()` you are getting list of responses. All the responses are `Response` object. You can access cookies by `res.cookies` 

For example, get the responses link this,
```
>>> response = fgreuests.build(urls, method='POST')
>>> print(response)
[<Response [405]>, <Response [200]>, <Response [200]>, <Response [200]>, None]
```
Now, you want to access the cookies of the first element of the response. You can do the following:

```
print(response[0].cookies)
```
